import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {sections} from './site';

// One autogenerated sidebar per top-level directory of the content root, keyed
// by the directory's name — the id the matching navbar item in
// docusaurus.config.ts names. Both come from the one list in site.ts, so a
// navbar item without its sidebar, or a sidebar over a directory that is not
// there, cannot be written.
const sidebars: SidebarsConfig = Object.fromEntries(
  sections.map(({name}) => [name, [{type: 'autogenerated' as const, dirName: name}]]),
);

export default sidebars;
